### ISSUE TITLE
Test for updating a request

### ISSUE THREAD

**Issue by LectureMonk** [parneetkj/Ibis#9]
There is an issue in _test_update_request_view.py_ where I am unable to test whether the database is correctly storing an updated request. On visual inspection this is working as required. 
A solution will need to be found before final submission, if anyone has any ideas how this could be tested let me know.

**Comment by parneetkj** [comment]
Could you try something similar to the clucker test for updating a profile ?
file:///home/parneet/Pictures/Screenshots/Screenshot%20from%202022-11-24%2013-59-07.png

**Comment by LectureMonk** [comment]
Test has been completed.
